services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: monitoring
      POSTGRES_PASSWORD: monitoring
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
